# Generated by Django 3.2 on 2021-04-12 07:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('marks_id', models.AutoField(primary_key=True, serialize=False)),
                ('mark', models.DecimalField(decimal_places=15, max_digits=30)),
                ('semester', models.CharField(default=None, max_length=100)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(default=None, max_length=100)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('age', models.IntegerField(unique=True)),
                ('address', models.TextField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('semester_name', models.CharField(max_length=100)),
                ('isactive', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
                ('mark', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentinfo.marks')),
            ],
        ),
    ]
