# Generated by Django 3.2 on 2021-04-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_modified_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester_name',
        ),
    ]
