# Generated by Django 3.2 on 2021-04-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0004_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='mark',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
